# Generated by Django 2.2.4 on 2019-09-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=123)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('pres_letter', models.TextField()),
                ('linkedin_link', models.URLField()),
                ('github_link', models.URLField()),
                ('eng_level', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('curriculum', models.FileField(upload_to='cv_upload')),
            ],
        ),
    ]
