# Generated by Django 2.2.4 on 2019-09-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='cv_upload'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default='default@default.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='eng_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(default='João', max_length=123),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='github_link',
            field=models.URLField(default='http://bing.com'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='linkedin_link',
            field=models.URLField(default='http://google.com'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.BigIntegerField(default=123456),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='pres_letter',
            field=models.TextField(default='Presentation letter'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=123.45, max_digits=10),
        ),
    ]
