# Generated by Django 2.2.4 on 2019-09-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190901_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='eng_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(max_length=123),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='github_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='linkedin_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='pres_letter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
