# Generated by Django 2.2.4 on 2019-09-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_candidate_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='datetime',
            field=models.DateField(),
        ),
    ]
