# Generated by Django 2.2.4 on 2019-09-04 21:42

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190902_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='curriculum',
            field=models.FileField(null=True, upload_to=website.models.upload_path),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='eng_level',
            field=models.CharField(choices=[('1', 'Iniciante'), ('2', 'Intermediário'), ('3', 'Avançado'), ('4', 'Nativo')], max_length=16),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='pres_letter',
            field=models.TextField(blank=True),
        ),
    ]
